server:
  port: 8083
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: yhzz
    password: root
    url: jdbc:oracle:thin:@localhost:1521:orcl
  application:
    name: user-provider
eureka:
  client:
    service-url:
      # EurekaServer的地址
      defaultZone: http://localhost:7001/eureka